### ISSUE TITLE
关于跟踪线程的延迟问题

### ISSUE THREAD

**Issue by q1vs5k5** [zlingkang/cv_thread_track_and_detect#1]
您好，十分感谢您开源的的工程，对我的开发非常有帮助，谢谢。但我发现在程序运行过程中总是存在跟踪线程滞后延迟很厉害，大概有34帧图像，所以想请教您有什么好的建议能尽可能降低这种情况吗？

**Comment by zlingkang** [comment]
你看一下readme 里面调sleep时间的方法和known issues 呢。 你一次track了多少个目标？ 多目标的话opencv这个就是很慢的，你可以看一下我另一个repo里我自己写的tracker，效果没这么好但跟踪多个目标的时候快多了https://github.com/zlingkang/multi_object_tracker
